// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/jflex/Scanner.jflex

package analisis;

import java_cup.runtime.Symbol;
import analisis.sym;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\2\22\0\1\1\1\4"+
    "\4\0\1\5\1\0\1\6\1\7\1\10\1\0\1\11"+
    "\1\0\1\12\1\13\12\14\1\15\1\0\1\16\1\17"+
    "\1\20\2\0\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\2\32\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\32\1\46\1\32\1\47\1\0\1\50\1\0\1\51"+
    "\1\0\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\2\32\1\63\1\64\1\65\1\66\1\67"+
    "\1\32\1\70\1\71\1\72\1\73\1\74\1\75\1\32"+
    "\1\76\1\32\1\77\1\100\1\101\7\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\1\1\12\10\13\1\14"+
    "\1\15\13\13\1\16\1\1\1\17\1\20\1\21\1\22"+
    "\1\2\1\0\1\23\1\24\1\25\14\13\1\26\14\13"+
    "\1\27\1\0\1\30\30\13\1\22\6\13\1\31\3\13"+
    "\1\32\4\13\1\33\5\13\1\34\1\13\1\35\10\13"+
    "\1\36\1\13\1\37\7\13\1\40\20\13\1\41\15\13"+
    "\1\42\2\13\1\43\10\13\1\44\1\13\1\45\3\13"+
    "\1\46\2\13\1\47\17\13\1\50\25\13\1\51\1\13"+
    "\1\52\13\13\1\53\3\13\1\54\1\55\1\13\1\56"+
    "\6\13\1\57\1\60\1\13\1\61\1\62\6\13\1\63"+
    "\5\13\1\64\1\13\1\65\1\66\2\13\1\67\1\70"+
    "\1\13\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[286];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\102\0\102\0\204\0\306\0\102\0\102\0\102"+
    "\0\u0108\0\u014a\0\102\0\u018c\0\u01ce\0\u0210\0\u0252\0\u0294"+
    "\0\u02d6\0\u0318\0\u035a\0\u039c\0\u03de\0\u0420\0\102\0\102"+
    "\0\u0462\0\u04a4\0\u04e6\0\u0528\0\u056a\0\u05ac\0\u05ee\0\u0630"+
    "\0\u0672\0\u06b4\0\u06f6\0\102\0\u0738\0\102\0\102\0\102"+
    "\0\u077a\0\u07bc\0\u07fe\0\102\0\102\0\102\0\u0840\0\u0882"+
    "\0\u08c4\0\u0906\0\u0948\0\u098a\0\u09cc\0\u0a0e\0\u0a50\0\u0a92"+
    "\0\u0ad4\0\u0b16\0\u0294\0\u0b58\0\u0b9a\0\u0bdc\0\u0c1e\0\u0c60"+
    "\0\u0ca2\0\u0ce4\0\u0d26\0\u0d68\0\u0daa\0\u0dec\0\u0e2e\0\102"+
    "\0\u0e70\0\u07fe\0\u0eb2\0\u0ef4\0\u0f36\0\u0f78\0\u0fba\0\u0ffc"+
    "\0\u103e\0\u1080\0\u10c2\0\u1104\0\u1146\0\u1188\0\u11ca\0\u120c"+
    "\0\u124e\0\u1290\0\u12d2\0\u1314\0\u1356\0\u1398\0\u13da\0\u141c"+
    "\0\u145e\0\u14a0\0\102\0\u14e2\0\u1524\0\u1566\0\u15a8\0\u15ea"+
    "\0\u162c\0\u0294\0\u166e\0\u16b0\0\u16f2\0\u0294\0\u1734\0\u1776"+
    "\0\u17b8\0\u17fa\0\u0294\0\u183c\0\u187e\0\u18c0\0\u1902\0\u1944"+
    "\0\u0294\0\u1986\0\u0294\0\u19c8\0\u1a0a\0\u1a4c\0\u1a8e\0\u1ad0"+
    "\0\u1b12\0\u1b54\0\u1b96\0\u0294\0\u1bd8\0\u0294\0\u1c1a\0\u1c5c"+
    "\0\u1c9e\0\u1ce0\0\u1d22\0\u1d64\0\u1da6\0\u0294\0\u1de8\0\u1e2a"+
    "\0\u1e6c\0\u1eae\0\u1ef0\0\u1f32\0\u1f74\0\u1fb6\0\u1ff8\0\u203a"+
    "\0\u207c\0\u20be\0\u2100\0\u2142\0\u2184\0\u21c6\0\u0294\0\u2208"+
    "\0\u224a\0\u228c\0\u22ce\0\u2310\0\u2352\0\u2394\0\u23d6\0\u2418"+
    "\0\u245a\0\u249c\0\u24de\0\u2520\0\u0294\0\u2562\0\u25a4\0\u0294"+
    "\0\u25e6\0\u2628\0\u266a\0\u26ac\0\u26ee\0\u2730\0\u2772\0\u27b4"+
    "\0\u0294\0\u27f6\0\u0294\0\u2838\0\u287a\0\u28bc\0\u0294\0\u28fe"+
    "\0\u2940\0\u2982\0\u29c4\0\u2a06\0\u2a48\0\u2a8a\0\u2acc\0\u2b0e"+
    "\0\u2b50\0\u2b92\0\u2bd4\0\u2c16\0\u2c58\0\u2c9a\0\u2cdc\0\u2d1e"+
    "\0\u2d60\0\u0294\0\u2da2\0\u2de4\0\u2e26\0\u2e68\0\u2eaa\0\u2eec"+
    "\0\u2f2e\0\u2f70\0\u2fb2\0\u2ff4\0\u3036\0\u3078\0\u30ba\0\u30fc"+
    "\0\u313e\0\u3180\0\u31c2\0\u3204\0\u3246\0\u3288\0\u32ca\0\u0294"+
    "\0\u330c\0\u0294\0\u334e\0\u3390\0\u33d2\0\u3414\0\u3456\0\u3498"+
    "\0\u34da\0\u351c\0\u355e\0\u35a0\0\u35e2\0\u0294\0\u3624\0\u3666"+
    "\0\u36a8\0\u0294\0\u0294\0\u36ea\0\u0294\0\u372c\0\u376e\0\u37b0"+
    "\0\u37f2\0\u3834\0\u3876\0\u0294\0\u0294\0\u38b8\0\u0294\0\u0294"+
    "\0\u38fa\0\u393c\0\u397e\0\u39c0\0\u3a02\0\u3a44\0\u0294\0\u3a86"+
    "\0\u3ac8\0\u3b0a\0\u3b4c\0\u3b8e\0\u0294\0\u3bd0\0\u0294\0\u0294"+
    "\0\u3c12\0\u3c54\0\u0294\0\u0294\0\u3c96\0\u0294";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[286];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\2"+
    "\1\10\1\2\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\4\20\1\21\1\20\1\22\4\20\1\23\2\20"+
    "\1\24\1\25\3\20\1\26\1\20\1\27\1\30\5\20"+
    "\1\31\1\32\1\33\1\20\1\34\1\35\1\36\1\20"+
    "\1\37\1\20\1\40\1\41\1\42\2\20\1\43\1\20"+
    "\1\44\1\45\1\46\121\0\1\47\67\0\1\50\104\0"+
    "\1\51\2\0\1\52\100\0\1\53\1\0\1\12\104\0"+
    "\1\54\101\0\1\55\101\0\1\56\76\0\1\20\4\0"+
    "\17\20\1\57\6\20\2\0\26\20\17\0\1\20\4\0"+
    "\26\20\2\0\26\20\17\0\1\20\4\0\10\20\1\60"+
    "\15\20\2\0\26\20\17\0\1\20\4\0\4\20\1\61"+
    "\21\20\2\0\26\20\17\0\1\20\4\0\1\62\3\20"+
    "\1\63\21\20\2\0\26\20\17\0\1\20\4\0\4\20"+
    "\1\64\21\20\2\0\26\20\17\0\1\20\4\0\7\20"+
    "\1\65\3\20\1\66\12\20\2\0\26\20\17\0\1\20"+
    "\4\0\1\67\25\20\2\0\26\20\17\0\1\20\4\0"+
    "\26\20\2\0\12\20\1\70\13\20\17\0\1\20\4\0"+
    "\26\20\2\0\1\20\1\71\24\20\17\0\1\20\4\0"+
    "\26\20\2\0\5\20\1\72\20\20\17\0\1\20\4\0"+
    "\26\20\2\0\6\20\1\73\5\20\1\74\11\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\20\1\75\24\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\20\1\76\24\20\17\0"+
    "\1\20\4\0\26\20\2\0\16\20\1\77\7\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\20\1\100\13\20\1\101"+
    "\4\20\1\102\3\20\17\0\1\20\4\0\26\20\2\0"+
    "\5\20\1\103\20\20\17\0\1\20\4\0\26\20\2\0"+
    "\10\20\1\104\4\20\1\105\1\20\1\106\6\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\20\1\107\24\20\103\0"+
    "\1\110\1\0\10\51\1\111\71\51\2\52\2\0\76\52"+
    "\14\0\1\112\101\0\1\20\4\0\2\20\1\113\23\20"+
    "\2\0\26\20\17\0\1\20\4\0\17\20\1\114\6\20"+
    "\2\0\26\20\17\0\1\20\4\0\1\115\25\20\2\0"+
    "\26\20\17\0\1\20\4\0\6\20\1\116\17\20\2\0"+
    "\26\20\17\0\1\20\4\0\3\20\1\117\22\20\2\0"+
    "\26\20\17\0\1\20\4\0\20\20\1\120\5\20\2\0"+
    "\26\20\17\0\1\20\4\0\10\20\1\121\15\20\2\0"+
    "\26\20\17\0\1\20\4\0\1\122\25\20\2\0\26\20"+
    "\17\0\1\20\4\0\17\20\1\123\6\20\2\0\26\20"+
    "\17\0\1\20\4\0\26\20\2\0\20\20\1\124\5\20"+
    "\17\0\1\20\4\0\26\20\2\0\12\20\1\125\13\20"+
    "\17\0\1\20\4\0\26\20\2\0\21\20\1\126\4\20"+
    "\17\0\1\20\4\0\26\20\2\0\11\20\1\127\14\20"+
    "\17\0\1\20\4\0\26\20\2\0\20\20\1\130\5\20"+
    "\17\0\1\20\4\0\26\20\2\0\7\20\1\131\16\20"+
    "\17\0\1\20\4\0\26\20\2\0\16\20\1\132\7\20"+
    "\17\0\1\20\4\0\26\20\2\0\14\20\1\133\11\20"+
    "\17\0\1\20\4\0\26\20\2\0\22\20\1\134\3\20"+
    "\17\0\1\20\4\0\26\20\2\0\12\20\1\135\13\20"+
    "\17\0\1\20\4\0\26\20\2\0\12\20\1\136\13\20"+
    "\17\0\1\20\4\0\26\20\2\0\5\20\1\137\20\20"+
    "\17\0\1\20\4\0\26\20\2\0\21\20\1\140\4\20"+
    "\17\0\1\20\4\0\26\20\2\0\22\20\1\141\3\20"+
    "\17\0\1\20\4\0\26\20\2\0\17\20\1\142\6\20"+
    "\3\0\10\51\1\111\2\51\1\143\66\51\14\0\1\20"+
    "\4\0\1\144\25\20\2\0\26\20\17\0\1\20\4\0"+
    "\4\20\1\145\21\20\2\0\26\20\17\0\1\20\4\0"+
    "\13\20\1\146\7\20\1\147\2\20\2\0\26\20\17\0"+
    "\1\20\4\0\10\20\1\150\15\20\2\0\26\20\17\0"+
    "\1\20\4\0\10\20\1\151\15\20\2\0\26\20\17\0"+
    "\1\20\4\0\21\20\1\152\4\20\2\0\26\20\17\0"+
    "\1\20\4\0\4\20\1\153\21\20\2\0\26\20\17\0"+
    "\1\20\4\0\20\20\1\154\5\20\2\0\26\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\155\25\20\17\0\1\20"+
    "\4\0\26\20\2\0\5\20\1\156\20\20\17\0\1\20"+
    "\4\0\26\20\2\0\20\20\1\157\5\20\17\0\1\20"+
    "\4\0\26\20\2\0\1\160\25\20\17\0\1\20\4\0"+
    "\26\20\2\0\21\20\1\161\4\20\17\0\1\20\4\0"+
    "\26\20\2\0\21\20\1\162\4\20\17\0\1\20\4\0"+
    "\26\20\2\0\5\20\1\163\20\20\17\0\1\20\4\0"+
    "\26\20\2\0\15\20\1\164\10\20\17\0\1\20\4\0"+
    "\26\20\2\0\4\20\1\165\21\20\17\0\1\20\4\0"+
    "\26\20\2\0\14\20\1\166\11\20\17\0\1\20\4\0"+
    "\26\20\2\0\5\20\1\167\20\20\17\0\1\20\4\0"+
    "\26\20\2\0\6\20\1\170\17\20\17\0\1\20\4\0"+
    "\26\20\2\0\14\20\1\171\11\20\17\0\1\20\4\0"+
    "\26\20\2\0\1\20\1\172\24\20\17\0\1\20\4\0"+
    "\26\20\2\0\5\20\1\173\20\20\17\0\1\20\4\0"+
    "\26\20\2\0\17\20\1\174\6\20\17\0\1\20\4\0"+
    "\15\20\1\175\10\20\2\0\26\20\17\0\1\20\4\0"+
    "\1\20\1\176\24\20\2\0\26\20\17\0\1\20\4\0"+
    "\10\20\1\177\15\20\2\0\26\20\17\0\1\20\4\0"+
    "\25\20\1\200\2\0\26\20\17\0\1\20\4\0\2\20"+
    "\1\201\23\20\2\0\26\20\17\0\1\20\4\0\21\20"+
    "\1\202\4\20\2\0\26\20\17\0\1\20\4\0\13\20"+
    "\1\203\12\20\2\0\26\20\17\0\1\20\4\0\7\20"+
    "\1\204\16\20\2\0\26\20\17\0\1\20\4\0\2\20"+
    "\1\205\23\20\2\0\26\20\17\0\1\20\4\0\26\20"+
    "\2\0\5\20\1\206\20\20\17\0\1\20\4\0\26\20"+
    "\2\0\12\20\1\207\1\210\12\20\17\0\1\20\4\0"+
    "\26\20\2\0\11\20\1\211\14\20\17\0\1\20\4\0"+
    "\26\20\2\0\1\212\25\20\17\0\1\20\4\0\26\20"+
    "\2\0\14\20\1\213\11\20\17\0\1\20\4\0\26\20"+
    "\2\0\15\20\1\214\10\20\17\0\1\20\4\0\26\20"+
    "\2\0\4\20\1\215\21\20\17\0\1\20\4\0\26\20"+
    "\2\0\20\20\1\216\5\20\17\0\1\20\4\0\26\20"+
    "\2\0\1\217\25\20\17\0\1\20\4\0\26\20\2\0"+
    "\12\20\1\220\13\20\17\0\1\20\4\0\26\20\2\0"+
    "\11\20\1\221\14\20\17\0\1\20\4\0\4\20\1\222"+
    "\21\20\2\0\26\20\17\0\1\20\4\0\1\223\25\20"+
    "\2\0\26\20\17\0\1\20\4\0\15\20\1\224\10\20"+
    "\2\0\26\20\17\0\1\20\4\0\26\20\2\0\1\225"+
    "\25\20\17\0\1\20\4\0\26\20\2\0\1\226\25\20"+
    "\17\0\1\20\4\0\1\227\25\20\2\0\26\20\17\0"+
    "\1\20\4\0\3\20\1\230\22\20\2\0\26\20\17\0"+
    "\1\20\4\0\17\20\1\231\6\20\2\0\26\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\20\1\232\24\20\17\0"+
    "\1\20\4\0\26\20\2\0\15\20\1\233\10\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\20\1\234\24\20\17\0"+
    "\1\20\4\0\26\20\2\0\13\20\1\235\12\20\17\0"+
    "\1\20\4\0\26\20\2\0\5\20\1\236\20\20\17\0"+
    "\1\20\4\0\26\20\2\0\13\20\1\237\12\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\240\25\20\17\0\1\20"+
    "\4\0\26\20\2\0\10\20\1\241\6\20\1\242\1\243"+
    "\5\20\17\0\1\20\4\0\26\20\2\0\1\244\25\20"+
    "\17\0\1\20\4\0\26\20\2\0\15\20\1\245\10\20"+
    "\17\0\1\20\4\0\26\20\2\0\1\246\25\20\17\0"+
    "\1\20\4\0\13\20\1\247\12\20\2\0\26\20\17\0"+
    "\1\20\4\0\6\20\1\250\17\20\2\0\26\20\17\0"+
    "\1\20\4\0\20\20\1\251\5\20\2\0\26\20\17\0"+
    "\1\20\4\0\1\20\1\252\24\20\2\0\26\20\17\0"+
    "\1\20\4\0\21\20\1\253\4\20\2\0\26\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\254\25\20\17\0\1\20"+
    "\4\0\25\20\1\255\2\0\26\20\17\0\1\20\4\0"+
    "\26\20\2\0\20\20\1\256\5\20\17\0\1\20\4\0"+
    "\26\20\2\0\23\20\1\257\2\20\17\0\1\20\4\0"+
    "\26\20\2\0\12\20\1\260\13\20\17\0\1\20\4\0"+
    "\26\20\2\0\15\20\1\261\10\20\17\0\1\20\4\0"+
    "\26\20\2\0\14\20\1\262\11\20\17\0\1\20\4\0"+
    "\26\20\2\0\14\20\1\263\11\20\17\0\1\20\4\0"+
    "\26\20\2\0\5\20\1\264\3\20\1\265\14\20\17\0"+
    "\1\20\4\0\26\20\2\0\5\20\1\266\20\20\17\0"+
    "\1\20\4\0\26\20\2\0\3\20\1\267\22\20\17\0"+
    "\1\20\4\0\26\20\2\0\17\20\1\270\6\20\17\0"+
    "\1\20\4\0\26\20\2\0\17\20\1\271\6\20\17\0"+
    "\1\20\4\0\1\20\1\272\24\20\2\0\26\20\17\0"+
    "\1\20\4\0\13\20\1\273\12\20\2\0\26\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\274\25\20\17\0\1\20"+
    "\4\0\21\20\1\275\4\20\2\0\26\20\17\0\1\20"+
    "\4\0\1\276\25\20\2\0\26\20\17\0\1\20\4\0"+
    "\4\20\1\277\21\20\2\0\26\20\17\0\1\20\4\0"+
    "\1\20\1\300\24\20\2\0\26\20\17\0\1\20\4\0"+
    "\26\20\2\0\21\20\1\301\4\20\17\0\1\20\4\0"+
    "\26\20\2\0\5\20\1\302\20\20\17\0\1\20\4\0"+
    "\26\20\2\0\23\20\1\303\2\20\17\0\1\20\4\0"+
    "\26\20\2\0\21\20\1\304\4\20\17\0\1\20\4\0"+
    "\26\20\2\0\22\20\1\305\3\20\17\0\1\20\4\0"+
    "\26\20\2\0\1\20\1\306\24\20\17\0\1\20\4\0"+
    "\26\20\2\0\20\20\1\307\5\20\17\0\1\20\4\0"+
    "\26\20\2\0\20\20\1\310\5\20\17\0\1\20\4\0"+
    "\26\20\2\0\15\20\1\311\10\20\17\0\1\20\4\0"+
    "\26\20\2\0\15\20\1\312\10\20\17\0\1\20\4\0"+
    "\16\20\1\313\7\20\2\0\26\20\17\0\1\20\4\0"+
    "\17\20\1\314\6\20\2\0\26\20\17\0\1\20\4\0"+
    "\17\20\1\315\6\20\2\0\26\20\17\0\1\20\4\0"+
    "\17\20\1\316\6\20\2\0\26\20\17\0\1\20\4\0"+
    "\13\20\1\317\12\20\2\0\26\20\17\0\1\20\4\0"+
    "\26\20\2\0\1\320\25\20\17\0\1\20\4\0\26\20"+
    "\2\0\20\20\1\321\5\20\17\0\1\20\4\0\26\20"+
    "\2\0\5\20\1\322\20\20\17\0\1\20\4\0\26\20"+
    "\2\0\1\323\25\20\17\0\1\20\4\0\26\20\2\0"+
    "\13\20\1\324\12\20\17\0\1\20\4\0\26\20\2\0"+
    "\12\20\1\325\13\20\17\0\1\20\4\0\26\20\2\0"+
    "\21\20\1\326\4\20\17\0\1\20\4\0\26\20\2\0"+
    "\15\20\1\327\10\20\17\0\1\20\4\0\26\20\2\0"+
    "\17\20\1\330\6\20\17\0\1\20\4\0\26\20\2\0"+
    "\22\20\1\331\3\20\17\0\1\20\4\0\13\20\1\332"+
    "\12\20\2\0\26\20\17\0\1\20\4\0\22\20\1\333"+
    "\3\20\2\0\26\20\17\0\1\20\4\0\10\20\1\334"+
    "\15\20\2\0\26\20\17\0\1\20\4\0\17\20\1\335"+
    "\6\20\2\0\26\20\17\0\1\20\4\0\16\20\1\336"+
    "\7\20\2\0\26\20\17\0\1\20\4\0\26\20\2\0"+
    "\14\20\1\337\11\20\17\0\1\20\4\0\26\20\2\0"+
    "\1\340\25\20\17\0\1\20\4\0\26\20\2\0\10\20"+
    "\1\341\6\20\1\342\1\343\5\20\17\0\1\20\4\0"+
    "\26\20\2\0\2\20\1\344\23\20\17\0\1\20\4\0"+
    "\26\20\2\0\21\20\1\345\4\20\17\0\1\20\4\0"+
    "\26\20\2\0\15\20\1\346\10\20\17\0\1\20\4\0"+
    "\26\20\2\0\22\20\1\347\3\20\17\0\1\20\4\0"+
    "\26\20\2\0\5\20\1\350\20\20\17\0\1\20\4\0"+
    "\26\20\2\0\14\20\1\351\11\20\17\0\1\20\4\0"+
    "\21\20\1\352\4\20\2\0\26\20\17\0\1\20\4\0"+
    "\15\20\1\353\10\20\2\0\26\20\17\0\1\20\4\0"+
    "\12\20\1\354\13\20\2\0\26\20\17\0\1\20\4\0"+
    "\10\20\1\355\15\20\2\0\26\20\17\0\1\20\4\0"+
    "\2\20\1\356\23\20\2\0\26\20\17\0\1\20\4\0"+
    "\26\20\2\0\1\357\25\20\17\0\1\20\4\0\26\20"+
    "\2\0\3\20\1\360\22\20\17\0\1\20\4\0\26\20"+
    "\2\0\5\20\1\361\3\20\1\362\14\20\17\0\1\20"+
    "\4\0\26\20\2\0\5\20\1\363\20\20\17\0\1\20"+
    "\4\0\26\20\2\0\3\20\1\364\22\20\17\0\1\20"+
    "\4\0\26\20\2\0\5\20\1\365\20\20\17\0\1\20"+
    "\4\0\26\20\2\0\10\20\1\366\15\20\17\0\1\20"+
    "\4\0\26\20\2\0\17\20\1\367\6\20\17\0\1\20"+
    "\4\0\26\20\2\0\17\20\1\370\6\20\17\0\1\20"+
    "\4\0\26\20\2\0\4\20\1\371\21\20\17\0\1\20"+
    "\4\0\4\20\1\372\21\20\2\0\26\20\17\0\1\20"+
    "\4\0\4\20\1\373\21\20\2\0\26\20\17\0\1\20"+
    "\4\0\4\20\1\374\21\20\2\0\26\20\17\0\1\20"+
    "\4\0\12\20\1\375\13\20\2\0\26\20\17\0\1\20"+
    "\4\0\26\20\2\0\13\20\1\376\12\20\17\0\1\20"+
    "\4\0\26\20\2\0\15\20\1\377\10\20\17\0\1\20"+
    "\4\0\26\20\2\0\1\20\1\u0100\24\20\17\0\1\20"+
    "\4\0\26\20\2\0\20\20\1\u0101\5\20\17\0\1\20"+
    "\4\0\26\20\2\0\20\20\1\u0102\5\20\17\0\1\20"+
    "\4\0\26\20\2\0\15\20\1\u0103\10\20\17\0\1\20"+
    "\4\0\26\20\2\0\17\20\1\u0104\6\20\17\0\1\20"+
    "\4\0\26\20\2\0\25\20\1\u0105\17\0\1\20\4\0"+
    "\26\20\2\0\3\20\1\u0106\22\20\17\0\1\20\4\0"+
    "\26\20\2\0\20\20\1\u0107\5\20\17\0\1\20\4\0"+
    "\17\20\1\u0108\6\20\2\0\26\20\17\0\1\20\4\0"+
    "\26\20\2\0\15\20\1\u0109\10\20\17\0\1\20\4\0"+
    "\26\20\2\0\22\20\1\u010a\3\20\17\0\1\20\4\0"+
    "\26\20\2\0\12\20\1\u010b\13\20\17\0\1\20\4\0"+
    "\26\20\2\0\21\20\1\u010c\4\20\17\0\1\20\4\0"+
    "\26\20\2\0\15\20\1\u010d\10\20\17\0\1\20\4\0"+
    "\26\20\2\0\17\20\1\u010e\6\20\17\0\1\20\4\0"+
    "\26\20\2\0\5\20\1\u010f\20\20\17\0\1\20\4\0"+
    "\26\20\2\0\23\20\1\u0110\2\20\17\0\1\20\4\0"+
    "\26\20\2\0\14\20\1\u0111\11\20\17\0\1\20\4\0"+
    "\26\20\2\0\21\20\1\u0112\4\20\17\0\1\20\4\0"+
    "\26\20\2\0\15\20\1\u0113\10\20\17\0\1\20\4\0"+
    "\26\20\2\0\22\20\1\u0114\3\20\17\0\1\20\4\0"+
    "\26\20\2\0\5\20\1\u0115\20\20\17\0\1\20\4\0"+
    "\26\20\2\0\5\20\1\u0116\20\20\17\0\1\20\4\0"+
    "\26\20\2\0\21\20\1\u0117\4\20\17\0\1\20\4\0"+
    "\26\20\2\0\10\20\1\u0118\15\20\17\0\1\20\4\0"+
    "\26\20\2\0\17\20\1\u0119\6\20\17\0\1\20\4\0"+
    "\26\20\2\0\17\20\1\u011a\6\20\17\0\1\20\4\0"+
    "\26\20\2\0\20\20\1\u011b\5\20\17\0\1\20\4\0"+
    "\26\20\2\0\25\20\1\u011c\17\0\1\20\4\0\26\20"+
    "\2\0\3\20\1\u011d\22\20\17\0\1\20\4\0\26\20"+
    "\2\0\5\20\1\u011e\20\20\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[15576];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\3\11\2\1\1\11\13\1\2\11"+
    "\13\1\1\11\1\1\3\11\2\1\1\0\3\11\31\1"+
    "\1\11\1\0\31\1\1\11\273\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[286];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    //Para crear objetos Symol con línea y columna
    private Symbol symbol(int type) {
        return new Symbol(type, yyline+1, yycolumn+ 1);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline +1, yycolumn+1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return symbol(sym.error, yytext());
            }
          // fall through
          case 58: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 59: break;
          case 3:
            { return symbol(sym.NOT);
            }
          // fall through
          case 60: break;
          case 4:
            { return symbol(sym.LPAREN);
            }
          // fall through
          case 61: break;
          case 5:
            { return symbol(sym.RPAREN);
            }
          // fall through
          case 62: break;
          case 6:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 63: break;
          case 7:
            { return symbol(sym.INTEGER, Integer.parseInt(yytext()));
            }
          // fall through
          case 64: break;
          case 8:
            { return symbol(sym.COLON);
            }
          // fall through
          case 65: break;
          case 9:
            { return symbol(sym.LT);
            }
          // fall through
          case 66: break;
          case 10:
            { return symbol(sym.GT);
            }
          // fall through
          case 67: break;
          case 11:
            { return symbol(sym.IDENTIFIER, yytext());
            }
          // fall through
          case 68: break;
          case 12:
            { return symbol(sym.LBRACKET);
            }
          // fall through
          case 69: break;
          case 13:
            { return symbol(sym.RBRACKET);
            }
          // fall through
          case 70: break;
          case 14:
            { return symbol(sym.LBRACE);
            }
          // fall through
          case 71: break;
          case 15:
            { return symbol(sym.RBRACE);
            }
          // fall through
          case 72: break;
          case 16:
            { return symbol(sym.NE);
            }
          // fall through
          case 73: break;
          case 17:
            { return symbol(sym.AND);
            }
          // fall through
          case 74: break;
          case 18:
            { 
            }
          // fall through
          case 75: break;
          case 19:
            { return symbol(sym.LE);
            }
          // fall through
          case 76: break;
          case 20:
            { return symbol(sym.EQ);
            }
          // fall through
          case 77: break;
          case 21:
            { return symbol(sym.GE);
            }
          // fall through
          case 78: break;
          case 22:
            { return symbol(sym.IF);
            }
          // fall through
          case 79: break;
          case 23:
            { return symbol(sym.OR);
            }
          // fall through
          case 80: break;
          case 24:
            { return new Symbol(sym.FLOAT, Double.parseDouble(yytext()));
            }
          // fall through
          case 81: break;
          case 25:
            { return symbol(sym.REST);
            }
          // fall through
          case 82: break;
          case 26:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 83: break;
          case 27:
            { return new Symbol(sym.MAGE, yytext());
            }
          // fall through
          case 84: break;
          case 28:
            { return symbol(sym.THEN);
            }
          // fall through
          case 85: break;
          case 29:
            { return symbol(sym.TRUE);
            }
          // fall through
          case 86: break;
          case 30:
            { return symbol(sym.SLASH);
            }
          // fall through
          case 87: break;
          case 31:
            { return symbol(sym.FALSE);
            }
          // fall through
          case 88: break;
          case 32:
            { return symbol(sym.RULES);
            }
          // fall through
          case 89: break;
          case 33:
            { return new Symbol(sym.RANDOM, yytext());
            }
          // fall through
          case 90: break;
          case 34:
            { return symbol(sym.WAR_CRY);
            }
          // fall through
          case 91: break;
          case 35:
            { return symbol(sym.INITIAL);
            }
          // fall through
          case 92: break;
          case 36:
            { return symbol(sym.WARRIOR);
            }
          // fall through
          case 93: break;
          case 37:
            { return symbol(sym.FIREBALL);
            }
          // fall through
          case 94: break;
          case 38:
            { return symbol(sym.MEDITATE);
            }
          // fall through
          case 95: break;
          case 39:
            { return new Symbol(sym.GET_MOVE, yytext());
            }
          // fall through
          case 96: break;
          case 40:
            { return new Symbol(sym.LAST_MOVE, yytext());
            }
          // fall through
          case 97: break;
          case 41:
            { return new Symbol(sym.SELF_SCORE, yytext());
            }
          // fall through
          case 98: break;
          case 42:
            { return symbol(sym.ARCANE_BOLT);
            }
          // fall through
          case 99: break;
          case 43:
            { return new Symbol(sym.SELF_HEALTH, yytext());
            }
          // fall through
          case 100: break;
          case 44:
            { return symbol(sym.HEALING_RUNE);
            }
          // fall through
          case 101: break;
          case 45:
            { return symbol(sym.HEAVY_STRIKE);
            }
          // fall through
          case 102: break;
          case 46:
            { return symbol(sym.SHIELD_BLOCK);
            }
          // fall through
          case 103: break;
          case 47:
            { return new Symbol(sym.ROUND_NUMBER, yytext());
            }
          // fall through
          case 104: break;
          case 48:
            { return new Symbol(sym.SELF_HISTORY, yytext());
            }
          // fall through
          case 105: break;
          case 49:
            { return new Symbol(sym.TOTAL_ROUNDS, yytext());
            }
          // fall through
          case 106: break;
          case 50:
            { return symbol(sym.MAGIC_BARRIER);
            }
          // fall through
          case 107: break;
          case 51:
            { return new Symbol(sym.SELF_RESOURCE, yytext());
            }
          // fall through
          case 108: break;
          case 52:
            { return new Symbol(sym.OPPONENT_SCORE, yytext());
            }
          // fall through
          case 109: break;
          case 53:
            { return new Symbol(sym.GET_MOVES_COUNT, yytext());
            }
          // fall through
          case 110: break;
          case 54:
            { return new Symbol(sym.OPPONENT_HEALTH, yytext());
            }
          // fall through
          case 111: break;
          case 55:
            { return new Symbol(sym.GET_LAST_N_MOVES, yytext());
            }
          // fall through
          case 112: break;
          case 56:
            { return new Symbol(sym.OPPONENT_HISTORY, yytext());
            }
          // fall through
          case 113: break;
          case 57:
            { return new Symbol(sym.OPPONENT_RESOURCE, yytext());
            }
          // fall through
          case 114: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
