
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

import java.util.List;
import java.util.ArrayList;
import java_cup.runtime.Symbol;
import ejecucion.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\116\000\002\002\004\000\002\002\005\000\002\004" +
    "\004\000\002\004\002\000\002\006\004\000\002\006\002" +
    "\000\002\003\016\000\002\003\016\000\002\016\003\000" +
    "\002\016\003\000\002\016\003\000\002\016\003\000\002" +
    "\016\003\000\002\016\003\000\002\016\003\000\002\016" +
    "\003\000\002\016\003\000\002\016\003\000\002\021\003" +
    "\000\002\021\005\000\002\020\006\000\002\022\006\000" +
    "\002\022\004\000\002\005\030\000\002\007\003\000\002" +
    "\007\005\000\002\010\025\000\002\011\031\000\002\012" +
    "\003\000\002\012\005\000\002\013\006\000\002\015\004" +
    "\000\002\015\002\000\002\014\014\000\002\023\003\000" +
    "\002\024\003\000\002\024\003\000\002\024\003\000\002" +
    "\024\005\000\002\024\005\000\002\024\004\000\002\024" +
    "\005\000\002\025\005\000\002\025\005\000\002\025\005" +
    "\000\002\025\005\000\002\025\005\000\002\025\005\000" +
    "\002\026\003\000\002\026\003\000\002\026\003\000\002" +
    "\026\003\000\002\026\003\000\002\026\003\000\002\026" +
    "\003\000\002\026\003\000\002\026\003\000\002\026\003" +
    "\000\002\026\003\000\002\026\003\000\002\026\003\000" +
    "\002\026\003\000\002\026\003\000\002\026\003\000\002" +
    "\026\003\000\002\026\003\000\002\026\003\000\002\026" +
    "\003\000\002\026\003\000\002\026\003\000\002\026\003" +
    "\000\002\026\003\000\002\026\003\000\002\026\003\000" +
    "\002\027\006\000\002\027\010\000\002\027\010\000\002" +
    "\027\010" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\330\000\012\004\007\005\004\052\ufffe\057\ufffe\001" +
    "\002\000\004\037\320\001\002\000\004\002\317\001\002" +
    "\000\012\004\007\005\004\052\ufffe\057\ufffe\001\002\000" +
    "\004\037\155\001\002\000\006\052\011\057\ufffc\001\002" +
    "\000\004\037\041\001\002\000\006\052\011\057\ufffc\001" +
    "\002\000\004\057\015\001\002\000\004\002\000\001\002" +
    "\000\004\015\016\001\002\000\006\016\uffe1\060\017\001" +
    "\002\000\004\017\024\001\002\000\006\016\uffe1\060\017" +
    "\001\002\000\004\016\022\001\002\000\004\002\uffe3\001" +
    "\002\000\004\016\uffe2\001\002\000\004\037\026\001\002" +
    "\000\006\014\027\020\030\001\002\000\006\014\uffe9\020" +
    "\uffe9\001\002\000\004\037\037\001\002\000\004\061\031" +
    "\001\002\000\004\015\032\001\002\000\004\062\033\001" +
    "\002\000\004\013\034\001\002\000\004\036\035\001\002" +
    "\000\004\016\036\001\002\000\006\016\uffe0\060\uffe0\001" +
    "\002\000\006\014\uffe8\020\uffe8\001\002\000\004\057\ufffd" +
    "\001\002\000\004\015\042\001\002\000\004\053\043\001" +
    "\002\000\004\013\044\001\002\000\004\017\045\001\002" +
    "\000\004\037\026\001\002\000\006\014\027\020\047\001" +
    "\002\000\004\054\050\001\002\000\004\013\051\001\002" +
    "\000\004\036\052\001\002\000\004\055\053\001\002\000" +
    "\004\013\054\001\002\000\004\015\055\001\002\000\004" +
    "\063\056\001\002\000\004\013\133\001\002\000\004\016" +
    "\060\001\002\000\004\056\061\001\002\000\004\013\062" +
    "\001\002\000\004\015\063\001\002\000\004\070\064\001" +
    "\002\000\004\013\070\001\002\000\004\016\066\001\002" +
    "\000\004\016\067\001\002\000\006\052\uffea\057\uffea\001" +
    "\002\000\004\017\071\001\002\000\026\040\105\041\075" +
    "\042\076\043\104\044\102\045\073\046\077\047\103\050" +
    "\074\051\072\001\002\000\012\007\ufff0\014\ufff0\020\ufff0" +
    "\022\ufff0\001\002\000\012\007\ufff4\014\ufff4\020\ufff4\022" +
    "\ufff4\001\002\000\012\007\ufff1\014\ufff1\020\ufff1\022\ufff1" +
    "\001\002\000\012\007\ufff8\014\ufff8\020\ufff8\022\ufff8\001" +
    "\002\000\012\007\ufff7\014\ufff7\020\ufff7\022\ufff7\001\002" +
    "\000\012\007\ufff3\014\ufff3\020\ufff3\022\ufff3\001\002\000" +
    "\006\014\uffe5\020\uffe5\001\002\000\006\014\106\020\107" +
    "\001\002\000\012\007\ufff5\014\ufff5\020\ufff5\022\ufff5\001" +
    "\002\000\012\007\ufff2\014\ufff2\020\ufff2\022\ufff2\001\002" +
    "\000\012\007\ufff6\014\ufff6\020\ufff6\022\ufff6\001\002\000" +
    "\012\007\ufff9\014\ufff9\020\ufff9\022\ufff9\001\002\000\026" +
    "\040\105\041\075\042\076\043\104\044\102\045\073\046" +
    "\077\047\103\050\074\051\072\001\002\000\004\014\110" +
    "\001\002\000\004\071\111\001\002\000\004\013\112\001" +
    "\002\000\004\036\113\001\002\000\004\014\114\001\002" +
    "\000\004\072\115\001\002\000\004\013\116\001\002\000" +
    "\004\017\117\001\002\000\026\040\105\041\075\042\076" +
    "\043\104\044\102\045\073\046\077\047\103\050\074\051" +
    "\072\001\002\000\006\014\106\020\121\001\002\000\004" +
    "\014\122\001\002\000\004\073\123\001\002\000\004\013" +
    "\124\001\002\000\004\036\125\001\002\000\004\014\126" +
    "\001\002\000\004\074\127\001\002\000\004\013\130\001" +
    "\002\000\004\036\131\001\002\000\004\016\uffe6\001\002" +
    "\000\006\014\uffe4\020\uffe4\001\002\000\004\036\134\001" +
    "\002\000\004\014\135\001\002\000\004\064\136\001\002" +
    "\000\004\013\137\001\002\000\004\036\140\001\002\000" +
    "\004\014\141\001\002\000\004\065\142\001\002\000\004" +
    "\013\143\001\002\000\004\036\144\001\002\000\004\014" +
    "\145\001\002\000\004\066\146\001\002\000\004\013\147" +
    "\001\002\000\004\036\150\001\002\000\004\014\151\001" +
    "\002\000\004\067\152\001\002\000\004\013\153\001\002" +
    "\000\004\036\154\001\002\000\004\016\uffe7\001\002\000" +
    "\004\015\156\001\002\000\004\006\157\001\002\000\004" +
    "\013\160\001\002\000\026\040\105\041\075\042\076\043" +
    "\104\044\102\045\073\046\077\047\103\050\074\051\072" +
    "\001\002\000\004\007\162\001\002\000\004\013\163\001" +
    "\002\000\004\017\164\001\002\000\006\010\171\012\166" +
    "\001\002\000\004\014\312\001\002\000\026\040\105\041" +
    "\075\042\076\043\104\044\102\045\073\046\077\047\103" +
    "\050\074\051\072\001\002\000\004\014\uffef\001\002\000" +
    "\004\020\307\001\002\000\100\021\206\033\211\034\215" +
    "\035\233\036\204\040\177\041\173\042\210\043\235\044" +
    "\201\045\202\046\176\047\207\050\231\051\223\075\220" +
    "\076\225\077\205\100\203\101\234\102\214\103\222\104" +
    "\216\105\175\106\221\107\232\110\227\111\224\112\226" +
    "\113\172\114\212\001\002\000\004\021\302\001\002\000" +
    "\030\011\uffc3\014\uffc3\022\uffc3\023\uffc3\024\uffc3\025\uffc3" +
    "\026\uffc3\027\uffc3\030\uffc3\031\uffc3\032\uffc3\001\002\000" +
    "\004\011\300\001\002\000\030\011\uffc7\014\uffc7\022\uffc7" +
    "\023\uffc7\024\uffc7\025\uffc7\026\uffc7\027\uffc7\030\uffc7\031" +
    "\uffc7\032\uffc7\001\002\000\030\011\uffbe\014\uffbe\022\uffbe" +
    "\023\uffbe\024\uffbe\025\uffbe\026\uffbe\027\uffbe\030\uffbe\031" +
    "\uffbe\032\uffbe\001\002\000\030\011\uffc4\014\uffc4\022\uffc4" +
    "\023\uffc4\024\uffc4\025\uffc4\026\uffc4\027\uffc4\030\uffc4\031" +
    "\uffc4\032\uffc4\001\002\000\012\011\uffde\022\uffde\031\uffde" +
    "\032\uffde\001\002\000\030\011\uffc0\014\uffc0\022\uffc0\023" +
    "\uffc0\024\uffc0\025\uffc0\026\uffc0\027\uffc0\030\uffc0\031\uffc0" +
    "\032\uffc0\001\002\000\030\011\uffbf\014\uffbf\022\uffbf\023" +
    "\uffbf\024\uffbf\025\uffbf\026\uffbf\027\uffbf\030\uffbf\031\uffbf" +
    "\032\uffbf\001\002\000\030\011\uffcc\014\uffcc\022\uffcc\023" +
    "\uffcc\024\uffcc\025\uffcc\026\uffcc\027\uffcc\030\uffcc\031\uffcc" +
    "\032\uffcc\001\002\000\030\011\uffd1\014\uffd1\022\uffd1\023" +
    "\uffd1\024\uffd1\025\uffd1\026\uffd1\027\uffd1\030\uffd1\031\uffd1" +
    "\032\uffd1\001\002\000\030\011\uffcd\014\uffcd\022\uffcd\023" +
    "\uffcd\024\uffcd\025\uffcd\026\uffcd\027\uffcd\030\uffcd\031\uffcd" +
    "\032\uffcd\001\002\000\100\021\206\033\211\034\215\035" +
    "\233\036\204\040\177\041\173\042\210\043\235\044\201" +
    "\045\202\046\176\047\207\050\231\051\223\075\220\076" +
    "\225\077\205\100\203\101\234\102\214\103\222\104\216" +
    "\105\175\106\221\107\232\110\227\111\224\112\226\113" +
    "\172\114\212\001\002\000\030\011\uffbd\014\uffbd\022\uffbd" +
    "\023\uffbd\024\uffbd\025\uffbd\026\uffbd\027\uffbd\030\uffbd\031" +
    "\uffbd\032\uffbd\001\002\000\030\011\uffc2\014\uffc2\022\uffc2" +
    "\023\uffc2\024\uffc2\025\uffc2\026\uffc2\027\uffc2\030\uffc2\031" +
    "\uffc2\032\uffc2\001\002\000\100\021\206\033\211\034\215" +
    "\035\233\036\204\040\177\041\173\042\210\043\235\044" +
    "\201\045\202\046\176\047\207\050\231\051\223\075\220" +
    "\076\225\077\205\100\203\101\234\102\214\103\222\104" +
    "\216\105\175\106\221\107\232\110\227\111\224\112\226" +
    "\113\172\114\212\001\002\000\004\021\270\001\002\000" +
    "\030\011\uffba\014\uffba\022\uffba\023\uffba\024\uffba\025\uffba" +
    "\026\uffba\027\uffba\030\uffba\031\uffba\032\uffba\001\002\000" +
    "\030\011\uffca\014\uffca\022\uffca\023\uffca\024\uffca\025\uffca" +
    "\026\uffca\027\uffca\030\uffca\031\uffca\032\uffca\001\002\000" +
    "\026\011\uffdd\022\uffdd\023\uffb9\024\uffb9\025\uffb9\026\uffb9" +
    "\027\uffb9\030\uffb9\031\uffdd\032\uffdd\001\002\000\030\011" +
    "\uffc8\014\uffc8\022\uffc8\023\uffc8\024\uffc8\025\uffc8\026\uffc8" +
    "\027\uffc8\030\uffc8\031\uffc8\032\uffc8\001\002\000\016\023" +
    "\255\024\261\025\256\026\254\027\260\030\257\001\002" +
    "\000\030\011\uffcf\014\uffcf\022\uffcf\023\uffcf\024\uffcf\025" +
    "\uffcf\026\uffcf\027\uffcf\030\uffcf\031\uffcf\032\uffcf\001\002" +
    "\000\030\011\uffc6\014\uffc6\022\uffc6\023\uffc6\024\uffc6\025" +
    "\uffc6\026\uffc6\027\uffc6\030\uffc6\031\uffc6\032\uffc6\001\002" +
    "\000\030\011\uffc9\014\uffc9\022\uffc9\023\uffc9\024\uffc9\025" +
    "\uffc9\026\uffc9\027\uffc9\030\uffc9\031\uffc9\032\uffc9\001\002" +
    "\000\030\011\uffbb\014\uffbb\022\uffbb\023\uffbb\024\uffbb\025" +
    "\uffbb\026\uffbb\027\uffbb\030\uffbb\031\uffbb\032\uffbb\001\002" +
    "\000\004\021\251\001\002\000\030\011\uffce\014\uffce\022" +
    "\uffce\023\uffce\024\uffce\025\uffce\026\uffce\027\uffce\030\uffce" +
    "\031\uffce\032\uffce\001\002\000\004\021\242\001\002\000" +
    "\030\011\uffd0\014\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0" +
    "\026\uffd0\027\uffd0\030\uffd0\031\uffd0\032\uffd0\001\002\000" +
    "\010\011\uffdf\031\236\032\237\001\002\000\030\011\uffbc" +
    "\014\uffbc\022\uffbc\023\uffbc\024\uffbc\025\uffbc\026\uffbc\027" +
    "\uffbc\030\uffbc\031\uffbc\032\uffbc\001\002\000\030\011\uffc5" +
    "\014\uffc5\022\uffc5\023\uffc5\024\uffc5\025\uffc5\026\uffc5\027" +
    "\uffc5\030\uffc5\031\uffc5\032\uffc5\001\002\000\026\011\uffdc" +
    "\022\uffdc\023\uffb8\024\uffb8\025\uffb8\026\uffb8\027\uffb8\030" +
    "\uffb8\031\uffdc\032\uffdc\001\002\000\030\011\uffcb\014\uffcb" +
    "\022\uffcb\023\uffcb\024\uffcb\025\uffcb\026\uffcb\027\uffcb\030" +
    "\uffcb\031\uffcb\032\uffcb\001\002\000\030\011\uffc1\014\uffc1" +
    "\022\uffc1\023\uffc1\024\uffc1\025\uffc1\026\uffc1\027\uffc1\030" +
    "\uffc1\031\uffc1\032\uffc1\001\002\000\100\021\206\033\211" +
    "\034\215\035\233\036\204\040\177\041\173\042\210\043" +
    "\235\044\201\045\202\046\176\047\207\050\231\051\223" +
    "\075\220\076\225\077\205\100\203\101\234\102\214\103" +
    "\222\104\216\105\175\106\221\107\232\110\227\111\224" +
    "\112\226\113\172\114\212\001\002\000\100\021\206\033" +
    "\211\034\215\035\233\036\204\040\177\041\173\042\210" +
    "\043\235\044\201\045\202\046\176\047\207\050\231\051" +
    "\223\075\220\076\225\077\205\100\203\101\234\102\214" +
    "\103\222\104\216\105\175\106\221\107\232\110\227\111" +
    "\224\112\226\113\172\114\212\001\002\000\012\011\uffda" +
    "\022\uffda\031\uffda\032\uffda\001\002\000\012\011\uffdb\022" +
    "\uffdb\031\uffdb\032\237\001\002\000\074\034\243\035\245" +
    "\036\204\040\177\041\173\042\210\043\235\044\201\045" +
    "\202\046\176\047\207\050\231\051\223\075\220\076\225" +
    "\077\205\100\203\101\234\102\214\103\222\104\216\105" +
    "\175\106\221\107\232\110\227\111\224\112\226\113\172" +
    "\114\212\001\002\000\014\011\uffb9\014\uffb9\022\uffb9\031" +
    "\uffb9\032\uffb9\001\002\000\004\014\246\001\002\000\014" +
    "\011\uffb8\014\uffb8\022\uffb8\031\uffb8\032\uffb8\001\002\000" +
    "\074\034\243\035\245\036\204\040\177\041\173\042\210" +
    "\043\235\044\201\045\202\046\176\047\207\050\231\051" +
    "\223\075\220\076\225\077\205\100\203\101\234\102\214" +
    "\103\222\104\216\105\175\106\221\107\232\110\227\111" +
    "\224\112\226\113\172\114\212\001\002\000\004\022\250" +
    "\001\002\000\030\011\uffb6\014\uffb6\022\uffb6\023\uffb6\024" +
    "\uffb6\025\uffb6\026\uffb6\027\uffb6\030\uffb6\031\uffb6\032\uffb6" +
    "\001\002\000\074\034\243\035\245\036\204\040\177\041" +
    "\173\042\210\043\235\044\201\045\202\046\176\047\207" +
    "\050\231\051\223\075\220\076\225\077\205\100\203\101" +
    "\234\102\214\103\222\104\216\105\175\106\221\107\232" +
    "\110\227\111\224\112\226\113\172\114\212\001\002\000" +
    "\004\022\253\001\002\000\030\011\uffb7\014\uffb7\022\uffb7" +
    "\023\uffb7\024\uffb7\025\uffb7\026\uffb7\027\uffb7\030\uffb7\031" +
    "\uffb7\032\uffb7\001\002\000\074\034\243\035\245\036\204" +
    "\040\177\041\173\042\210\043\235\044\201\045\202\046" +
    "\176\047\207\050\231\051\223\075\220\076\225\077\205" +
    "\100\203\101\234\102\214\103\222\104\216\105\175\106" +
    "\221\107\232\110\227\111\224\112\226\113\172\114\212" +
    "\001\002\000\074\034\243\035\245\036\204\040\177\041" +
    "\173\042\210\043\235\044\201\045\202\046\176\047\207" +
    "\050\231\051\223\075\220\076\225\077\205\100\203\101" +
    "\234\102\214\103\222\104\216\105\175\106\221\107\232" +
    "\110\227\111\224\112\226\113\172\114\212\001\002\000" +
    "\074\034\243\035\245\036\204\040\177\041\173\042\210" +
    "\043\235\044\201\045\202\046\176\047\207\050\231\051" +
    "\223\075\220\076\225\077\205\100\203\101\234\102\214" +
    "\103\222\104\216\105\175\106\221\107\232\110\227\111" +
    "\224\112\226\113\172\114\212\001\002\000\074\034\243" +
    "\035\245\036\204\040\177\041\173\042\210\043\235\044" +
    "\201\045\202\046\176\047\207\050\231\051\223\075\220" +
    "\076\225\077\205\100\203\101\234\102\214\103\222\104" +
    "\216\105\175\106\221\107\232\110\227\111\224\112\226" +
    "\113\172\114\212\001\002\000\074\034\243\035\245\036" +
    "\204\040\177\041\173\042\210\043\235\044\201\045\202" +
    "\046\176\047\207\050\231\051\223\075\220\076\225\077" +
    "\205\100\203\101\234\102\214\103\222\104\216\105\175" +
    "\106\221\107\232\110\227\111\224\112\226\113\172\114" +
    "\212\001\002\000\074\034\243\035\245\036\204\040\177" +
    "\041\173\042\210\043\235\044\201\045\202\046\176\047" +
    "\207\050\231\051\223\075\220\076\225\077\205\100\203" +
    "\101\234\102\214\103\222\104\216\105\175\106\221\107" +
    "\232\110\227\111\224\112\226\113\172\114\212\001\002" +
    "\000\012\011\uffd6\022\uffd6\031\uffd6\032\uffd6\001\002\000" +
    "\012\011\uffd2\022\uffd2\031\uffd2\032\uffd2\001\002\000\012" +
    "\011\uffd4\022\uffd4\031\uffd4\032\uffd4\001\002\000\012\011" +
    "\uffd3\022\uffd3\031\uffd3\032\uffd3\001\002\000\012\011\uffd7" +
    "\022\uffd7\031\uffd7\032\uffd7\001\002\000\012\011\uffd5\022" +
    "\uffd5\031\uffd5\032\uffd5\001\002\000\074\034\243\035\245" +
    "\036\204\040\177\041\173\042\210\043\235\044\201\045" +
    "\202\046\176\047\207\050\231\051\223\075\220\076\225" +
    "\077\205\100\203\101\234\102\214\103\222\104\216\105" +
    "\175\106\221\107\232\110\227\111\224\112\226\113\172" +
    "\114\212\001\002\000\004\014\272\001\002\000\074\034" +
    "\243\035\245\036\204\040\177\041\173\042\210\043\235" +
    "\044\201\045\202\046\176\047\207\050\231\051\223\075" +
    "\220\076\225\077\205\100\203\101\234\102\214\103\222" +
    "\104\216\105\175\106\221\107\232\110\227\111\224\112" +
    "\226\113\172\114\212\001\002\000\004\022\274\001\002" +
    "\000\030\011\uffb4\014\uffb4\022\uffb4\023\uffb4\024\uffb4\025" +
    "\uffb4\026\uffb4\027\uffb4\030\uffb4\031\uffb4\032\uffb4\001\002" +
    "\000\012\011\uffd9\022\uffd9\031\236\032\237\001\002\000" +
    "\010\022\277\031\236\032\237\001\002\000\012\011\uffd8" +
    "\022\uffd8\031\uffd8\032\uffd8\001\002\000\026\040\105\041" +
    "\075\042\076\043\104\044\102\045\073\046\077\047\103" +
    "\050\074\051\072\001\002\000\004\014\uffed\001\002\000" +
    "\074\034\243\035\245\036\204\040\177\041\173\042\210" +
    "\043\235\044\201\045\202\046\176\047\207\050\231\051" +
    "\223\075\220\076\225\077\205\100\203\101\234\102\214" +
    "\103\222\104\216\105\175\106\221\107\232\110\227\111" +
    "\224\112\226\113\172\114\212\001\002\000\004\014\304" +
    "\001\002\000\026\040\105\041\075\042\076\043\104\044" +
    "\102\045\073\046\077\047\103\050\074\051\072\001\002" +
    "\000\004\022\306\001\002\000\030\011\uffb5\014\uffb5\022" +
    "\uffb5\023\uffb5\024\uffb5\025\uffb5\026\uffb5\027\uffb5\030\uffb5" +
    "\031\uffb5\032\uffb5\001\002\000\004\016\310\001\002\000" +
    "\012\004\ufffb\005\ufffb\052\ufffb\057\ufffb\001\002\000\004" +
    "\020\uffeb\001\002\000\006\010\171\012\313\001\002\000" +
    "\026\040\105\041\075\042\076\043\104\044\102\045\073" +
    "\046\077\047\103\050\074\051\072\001\002\000\004\014" +
    "\uffee\001\002\000\004\020\uffec\001\002\000\006\052\uffff" +
    "\057\uffff\001\002\000\004\002\001\001\002\000\004\015" +
    "\321\001\002\000\004\006\322\001\002\000\004\013\323" +
    "\001\002\000\026\040\105\041\075\042\076\043\104\044" +
    "\102\045\073\046\077\047\103\050\074\051\072\001\002" +
    "\000\004\007\325\001\002\000\004\013\326\001\002\000" +
    "\004\017\327\001\002\000\006\010\171\012\166\001\002" +
    "\000\004\020\331\001\002\000\004\016\332\001\002\000" +
    "\012\004\ufffa\005\ufffa\052\ufffa\057\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\330\000\010\002\004\003\005\004\007\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\003\005\004\315" +
    "\001\001\000\002\001\001\000\006\005\011\006\012\001" +
    "\001\000\002\001\001\000\006\005\011\006\037\001\001" +
    "\000\004\013\013\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\014\017\015\020\001\001\000\002\001\001" +
    "\000\006\014\017\015\022\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\024\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\010\056\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\064\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\012\100\016\077" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\016\131\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\012" +
    "\117\016\077\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\016\160\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\020\166\021" +
    "\164\022\167\001\001\000\002\001\001\000\004\016\310" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\023" +
    "\173\024\227\025\177\026\216\027\212\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\024\275\025\177" +
    "\026\216\027\212\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\024\274\025\177\026\216\027\212\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\024\240\025\177\026\216\027\212\001" +
    "\001\000\012\024\237\025\177\026\216\027\212\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\026\243\027" +
    "\212\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\026\246\027\212\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\026\251\027\212\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\026\266\027" +
    "\212\001\001\000\006\026\265\027\212\001\001\000\006" +
    "\026\264\027\212\001\001\000\006\026\263\027\212\001" +
    "\001\000\006\026\262\027\212\001\001\000\006\026\261" +
    "\027\212\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\026\270\027\212\001\001\000\002\001" +
    "\001\000\006\026\272\027\212\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\016\300\001\001\000\002\001\001" +
    "\000\006\026\302\027\212\001\001\000\002\001\001\000" +
    "\004\016\304\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\313\001\001\000\004\016\314\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\016\323\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\020\166\021\164\022\327" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= strategy_list match_list main_block 
            {
              Program RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List sl = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int mlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int mlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List ml = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int mbleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int mbright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		MainBlock mb = (MainBlock)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Program(sl, ml, mb);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // strategy_list ::= strategy strategy_list 
            {
              List RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Strategy s = (Strategy)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int restleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int restright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		List rest = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        rest.add(0, s);
        RESULT = rest;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("strategy_list",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // strategy_list ::= 
            {
              List RESULT =null;
		
        RESULT = new ArrayList<Strategy>();
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("strategy_list",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // match_list ::= match match_list 
            {
              List RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Match m = (Match)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int restleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int restright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		List rest = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        rest.add(0, m);
        RESULT = rest;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("match_list",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // match_list ::= 
            {
              List RESULT =null;
		
        RESULT = new ArrayList<Match>();
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("match_list",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // strategy ::= MAGE IDENTIFIER LBRACE INITIAL COLON accion RULES COLON LBRACKET rules_content RBRACKET RBRACE 
            {
              Strategy RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-10)).value;
		int actleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int actright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		ActionType act = (ActionType)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int rcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int rcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object rc = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
        List<Rule> rules = (List<Rule>) ((Object[])rc)[0];
        ActionType defAct = (ActionType) ((Object[])rc)[1];
        RESULT = new Strategy(id, true, (ActionType)act, rules, defAct);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("strategy",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // strategy ::= WARRIOR IDENTIFIER LBRACE INITIAL COLON accion RULES COLON LBRACKET rules_content RBRACKET RBRACE 
            {
              Strategy RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-10)).value;
		int actleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int actright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		ActionType act = (ActionType)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int rcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int rcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object rc = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
        List<Rule> rules = (List<Rule>) ((Object[])rc)[0];
        ActionType defAct = (ActionType) ((Object[])rc)[1];
        RESULT = new Strategy(id, false, (ActionType)act, rules, defAct);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("strategy",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // accion ::= ARCANE_BOLT 
            {
              ActionType RESULT =null;
		 RESULT = ActionType.ARCANE_BOLT; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // accion ::= FIREBALL 
            {
              ActionType RESULT =null;
		 RESULT = ActionType.FIREBALL; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // accion ::= MAGIC_BARRIER 
            {
              ActionType RESULT =null;
		 RESULT = ActionType.MAGIC_BARRIER; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // accion ::= HEALING_RUNE 
            {
              ActionType RESULT =null;
		 RESULT = ActionType.HEALING_RUNE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // accion ::= MEDITATE 
            {
              ActionType RESULT =null;
		 RESULT = ActionType.MEDITATE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // accion ::= SLASH 
            {
              ActionType RESULT =null;
		 RESULT = ActionType.SLASH; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // accion ::= HEAVY_STRIKE 
            {
              ActionType RESULT =null;
		 RESULT = ActionType.HEAVY_STRIKE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // accion ::= SHIELD_BLOCK 
            {
              ActionType RESULT =null;
		 RESULT = ActionType.SHIELD_BLOCK; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // accion ::= WAR_CRY 
            {
              ActionType RESULT =null;
		 RESULT = ActionType.WAR_CRY; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // accion ::= REST 
            {
              ActionType RESULT =null;
		 RESULT = ActionType.REST; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // rule_list ::= rule 
            {
              List RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Rule r = (Rule)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ArrayList<Rule>(); ((List<Rule>)RESULT).add(r); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("rule_list",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // rule_list ::= rule_list COMMA rule 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Rule r = (Rule)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 l.add(r); RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("rule_list",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // rule ::= IF condition THEN accion 
            {
              Rule RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Condition c = (Condition)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ActionType a = (ActionType)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Rule((Condition)c, (ActionType)a); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("rule",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // rules_content ::= rule_list COMMA ELSE accion 
            {
              Object RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ActionType a = (ActionType)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Object[]{l, a}; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("rules_content",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // rules_content ::= ELSE accion 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ActionType a = (ActionType)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Object[]{new ArrayList<Rule>(), a}; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("rules_content",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // match ::= MATCH IDENTIFIER LBRACE PLAYERS COLON LBRACKET identifier_list RBRACKET ROUNDS COLON INTEGER SCORING COLON LBRACE scoring_block RBRACE BONUSES COLON LBRACE bonuses_block RBRACE RBRACE 
            {
              Match RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-20)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-20)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-20)).value;
		int playersleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-15)).left;
		int playersright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-15)).right;
		List players = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-15)).value;
		int roundsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).left;
		int roundsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).right;
		Integer rounds = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-11)).value;
		int scleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int scright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Scoring sc = (Scoring)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int bonleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int bonright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Bonuses bon = (Bonuses)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
        RESULT = new Match(name, players, rounds, sc, bon);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("match",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-21)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // identifier_list ::= IDENTIFIER 
            {
              List RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT =new ArrayList<String>();
        ((List<String>)RESULT).add(id);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("identifier_list",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // identifier_list ::= identifier_list COMMA IDENTIFIER 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        l.add(id);
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("identifier_list",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // scoring_block ::= DAMAGE_POINT COLON INTEGER COMMA HEALING_POINT COLON INTEGER COMMA SUCCESSFUL_DEFENSE COLON INTEGER COMMA VICTORY_BONUS COLON INTEGER COMMA FAILED_ACTION_PENALTY COLON INTEGER 
            {
              Scoring RESULT =null;
		int dpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-16)).left;
		int dpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-16)).right;
		Integer dp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-16)).value;
		int hpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)).left;
		int hpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)).right;
		Integer hp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-12)).value;
		int sdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).left;
		int sdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).right;
		Integer sd = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-8)).value;
		int vbleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int vbright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Integer vb = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int fpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer fp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT =new Scoring(dp, hp, sd, vb, fp);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("scoring_block",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-18)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // bonuses_block ::= MAGE_COMBO COLON LBRACKET action_list RBRACKET COMMA MAGE_COMBO_POINTS COLON INTEGER COMMA WARRIOR_COMBO COLON LBRACKET action_list RBRACKET COMMA WARRIOR_COMBO_POINTS COLON INTEGER COMMA LOW_HEALTH_VICTORY COLON INTEGER 
            {
              Bonuses RESULT =null;
		int mcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-19)).left;
		int mcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-19)).right;
		List mc = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-19)).value;
		int mcpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)).left;
		int mcpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)).right;
		Integer mcp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-14)).value;
		int wcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)).left;
		int wcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)).right;
		List wc = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-9)).value;
		int wcpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int wcpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Integer wcp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int lhleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lhright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer lh = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT=new Bonuses(mc, mcp, wc, wcp, lh);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bonuses_block",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-22)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // action_list ::= accion 
            {
              List RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ActionType a = (ActionType)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new ArrayList<ActionType>();
        ((List<ActionType>)RESULT).add(a);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("action_list",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // action_list ::= action_list COMMA accion 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ActionType a = (ActionType)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        l.add(a);
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("action_list",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // main_block ::= MAIN LBRACE run_list RBRACE 
            {
              MainBlock RESULT =null;
		int runsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int runsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List runs = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new MainBlock(runs);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("main_block",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // run_list ::= run_instruction run_list 
            {
              List RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Run r = (Run)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int restleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int restright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		List rest = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        rest.add(0, r);
        RESULT = rest;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("run_list",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // run_list ::= 
            {
              List RESULT =null;
		
        RESULT = new ArrayList<Run>();
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("run_list",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // run_instruction ::= RUN LBRACKET identifier_list RBRACKET WITH LBRACE SEED COLON INTEGER RBRACE 
            {
              Run RESULT =null;
		int namesleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int namesright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		List names = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int seedleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int seedright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer seed = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Run(names, seed);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("run_instruction",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condition ::= expr 
            {
              Condition RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Condition e = (Condition)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (Condition) e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= comparacion 
            {
              Condition RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Condition c = (Condition)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= TRUE 
            {
              Condition RESULT =null;
		 RESULT = (Condition) (ctx -> true); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= FALSE 
            {
              Condition RESULT =null;
		 RESULT = (Condition) (ctx -> false); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= expr AND expr 
            {
              Condition RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Condition e1 = (Condition)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Condition e2 = (Condition)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (Condition) (ctx -> ((Condition)e1).evaluate(ctx) && ((Condition)e2).evaluate(ctx)); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= expr OR expr 
            {
              Condition RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Condition e1 = (Condition)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Condition e2 = (Condition)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (Condition) (ctx -> ((Condition)e1).evaluate(ctx) || ((Condition)e2).evaluate(ctx)); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= NOT expr 
            {
              Condition RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Condition e = (Condition)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (Condition) (ctx -> !((Condition)e).evaluate(ctx)); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= LPAREN expr RPAREN 
            {
              Condition RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Condition e = (Condition)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // comparacion ::= valor EQ valor 
            {
              Condition RESULT =null;
		int v1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int v2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int v2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object v2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (Condition) (ctx -> v1.equals(v2)); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // comparacion ::= valor NE valor 
            {
              Condition RESULT =null;
		int v1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int v2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int v2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object v2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (Condition) (ctx -> !v1.equals(v2)); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // comparacion ::= valor LT valor 
            {
              Condition RESULT =null;
		int v1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int v2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int v2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object v2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (Condition) (ctx -> ((Number)v1).doubleValue() < ((Number)v2).doubleValue()); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // comparacion ::= valor LE valor 
            {
              Condition RESULT =null;
		int v1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int v2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int v2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object v2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (Condition) (ctx -> ((Number)v1).doubleValue() <= ((Number)v2).doubleValue()); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // comparacion ::= valor GT valor 
            {
              Condition RESULT =null;
		int v1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int v2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int v2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object v2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (Condition) (ctx -> ((Number)v1).doubleValue() > ((Number)v2).doubleValue()); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // comparacion ::= valor GE valor 
            {
              Condition RESULT =null;
		int v1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int v2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int v2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object v2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = (Condition) (ctx -> ((Number)v1).doubleValue() >= ((Number)v2).doubleValue()); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // valor ::= INTEGER 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // valor ::= FLOAT 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Float f = (Float)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // valor ::= SELF_HEALTH 
            {
              Object RESULT =null;
		 RESULT = "self_health"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // valor ::= OPPONENT_HEALTH 
            {
              Object RESULT =null;
		 RESULT = "opponent_health"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // valor ::= SELF_RESOURCE 
            {
              Object RESULT =null;
		 RESULT = "self_resource"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // valor ::= OPPONENT_RESOURCE 
            {
              Object RESULT =null;
		 RESULT = "opponent_resource"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // valor ::= SELF_SCORE 
            {
              Object RESULT =null;
		 RESULT = "self_score"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // valor ::= OPPONENT_SCORE 
            {
              Object RESULT =null;
		 RESULT = "opponent_score"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // valor ::= ROUND_NUMBER 
            {
              Object RESULT =null;
		 RESULT = "round_number"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // valor ::= TOTAL_ROUNDS 
            {
              Object RESULT =null;
		 RESULT = "total_rounds"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // valor ::= RANDOM 
            {
              Object RESULT =null;
		 RESULT = "random"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // valor ::= SELF_HISTORY 
            {
              Object RESULT =null;
		 RESULT = "self_history"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // valor ::= OPPONENT_HISTORY 
            {
              Object RESULT =null;
		 RESULT = "opponent_history"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // valor ::= ARCANE_BOLT 
            {
              Object RESULT =null;
		 RESULT = ActionType.ARCANE_BOLT; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // valor ::= FIREBALL 
            {
              Object RESULT =null;
		 RESULT = ActionType.FIREBALL; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // valor ::= MAGIC_BARRIER 
            {
              Object RESULT =null;
		 RESULT = ActionType.MAGIC_BARRIER; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // valor ::= HEALING_RUNE 
            {
              Object RESULT =null;
		 RESULT = ActionType.HEALING_RUNE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // valor ::= MEDITATE 
            {
              Object RESULT =null;
		 RESULT = ActionType.MEDITATE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // valor ::= SLASH 
            {
              Object RESULT =null;
		 RESULT = ActionType.SLASH; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // valor ::= HEAVY_STRIKE 
            {
              Object RESULT =null;
		 RESULT = ActionType.HEAVY_STRIKE; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // valor ::= SHIELD_BLOCK 
            {
              Object RESULT =null;
		 RESULT = ActionType.SHIELD_BLOCK; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // valor ::= WAR_CRY 
            {
              Object RESULT =null;
		 RESULT = ActionType.WAR_CRY; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // valor ::= REST 
            {
              Object RESULT =null;
		 RESULT = ActionType.REST; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // valor ::= llamada 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // valor ::= TRUE 
            {
              Object RESULT =null;
		 RESULT = true; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // valor ::= FALSE 
            {
              Object RESULT =null;
		 RESULT = false; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // llamada ::= LAST_MOVE LPAREN valor RPAREN 
            {
              Object RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object h = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = ActionType.ARCANE_BOLT; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("llamada",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // llamada ::= GET_MOVE LPAREN valor COMMA valor RPAREN 
            {
              Object RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object h = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = ActionType.ARCANE_BOLT; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("llamada",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // llamada ::= GET_MOVES_COUNT LPAREN valor COMMA accion RPAREN 
            {
              Object RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object h = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ActionType a = (ActionType)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = Integer.valueOf(0); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("llamada",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // llamada ::= GET_LAST_N_MOVES LPAREN valor COMMA valor RPAREN 
            {
              Object RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object h = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new ArrayList<ActionType>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("llamada",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
