
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACKET = 13;
  public static final int FIREBALL = 31;
  public static final int RANDOM = 48;
  public static final int HEAVY_STRIKE = 36;
  public static final int GE = 21;
  public static final int ARCANE_BOLT = 30;
  public static final int SLASH = 35;
  public static final int MEDITATE = 34;
  public static final int OPPONENT_RESOURCE = 43;
  public static final int SELF_RESOURCE = 42;
  public static final int INTEGER = 28;
  public static final int LPAREN = 15;
  public static final int MAGE = 2;
  public static final int SHIELD_BLOCK = 37;
  public static final int MAGIC_BARRIER = 32;
  public static final int RULES = 5;
  public static final int RPAREN = 16;
  public static final int NOT = 25;
  public static final int AND = 23;
  public static final int LT = 20;
  public static final int OR = 24;
  public static final int COMMA = 10;
  public static final int OPPONENT_SCORE = 45;
  public static final int IF = 6;
  public static final int LE = 22;
  public static final int INITIAL = 4;
  public static final int EOF = 0;
  public static final int RBRACKET = 14;
  public static final int TRUE = 26;
  public static final int error = 1;
  public static final int TOTAL_ROUNDS = 47;
  public static final int EQ = 17;
  public static final int SELF_HEALTH = 40;
  public static final int SELF_HISTORY = 49;
  public static final int ROUND_NUMBER = 46;
  public static final int COLON = 9;
  public static final int REST = 39;
  public static final int LBRACE = 11;
  public static final int ELSE = 8;
  public static final int OPPONENT_HEALTH = 41;
  public static final int FLOAT = 51;
  public static final int THEN = 7;
  public static final int RBRACE = 12;
  public static final int NE = 18;
  public static final int WAR_CRY = 38;
  public static final int WARRIOR = 3;
  public static final int OPPONENT_HISTORY = 50;
  public static final int FALSE = 27;
  public static final int SELF_SCORE = 44;
  public static final int GT = 19;
  public static final int HEALING_RUNE = 33;
  public static final int IDENTIFIER = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAGE",
  "WARRIOR",
  "INITIAL",
  "RULES",
  "IF",
  "THEN",
  "ELSE",
  "COLON",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "EQ",
  "NE",
  "GT",
  "LT",
  "GE",
  "LE",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "INTEGER",
  "IDENTIFIER",
  "ARCANE_BOLT",
  "FIREBALL",
  "MAGIC_BARRIER",
  "HEALING_RUNE",
  "MEDITATE",
  "SLASH",
  "HEAVY_STRIKE",
  "SHIELD_BLOCK",
  "WAR_CRY",
  "REST",
  "SELF_HEALTH",
  "OPPONENT_HEALTH",
  "SELF_RESOURCE",
  "OPPONENT_RESOURCE",
  "SELF_SCORE",
  "OPPONENT_SCORE",
  "ROUND_NUMBER",
  "TOTAL_ROUNDS",
  "RANDOM",
  "SELF_HISTORY",
  "OPPONENT_HISTORY",
  "FLOAT"
  };
}

